### ISSUE TITLE
sh: 1: ./wait-for: not found

### ISSUE THREAD

**Issue by ibakayoko** [mrako/wait-for#1]
i created a docker-compose.yaml with the content below

```
version: '2'

services:
  db:
    image: postgres:9.4

  backend:
    image: tomcat
    command: sh -c './wait-for db:5432 -- npm start'
    depends_on:
      - db
```

the backend service is not starting i get 
```
sh: 1: ./wait-for: not found
```

in the container log.
